services:
  front:
    container_name: front
    build:
      context: .
      target: dev
      dockerfile: ./docker/front/Dockerfile
    volumes:
      - type: bind
        source: ./front
        target: /app
      - type: volume
        source: node-modules-volume
        target: /app/node_modules
    ports:
      - 5173:5173
      - 4173:4173
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    volumes:
      - ./backend:/app
    tty: true
    ports:
      - 8080:8080
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cist_ptj
      MYSQL_USER: user1
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/entry:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: cist_ptj
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8081:80"
    depends_on:
      - mysql
volumes:
  node-modules-volume:
