services:
  front:
    container_name: front
    build:
      context: .
      target: dev
      dockerfile: ./docker/front/Dockerfile
    volumes:
      - type: bind
        source: ./front
        target: /app
      - type: volume
        source: node-modules-volume
        target: /app/node_modules
    ports:
      - 5173:5173
      - 4173:4173
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  node-modules-volume:
